package com.cycfc.demo.provider.dao;

import com.cycfc.demo.provider.model.TbDemo;
import com.cycfc.demo.provider.model.TbDemoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbDemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Sat Sep 08 15:58:17 CST 2018
     */
    long countByExample(TbDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Sat Sep 08 15:58:17 CST 2018
     */
    int deleteByExample(TbDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Sat Sep 08 15:58:17 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Sat Sep 08 15:58:17 CST 2018
     */
    int insert(TbDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Sat Sep 08 15:58:17 CST 2018
     */
    int insertSelective(TbDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Sat Sep 08 15:58:17 CST 2018
     */
    List<TbDemo> selectByExample(TbDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Sat Sep 08 15:58:17 CST 2018
     */
    TbDemo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Sat Sep 08 15:58:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbDemo record, @Param("example") TbDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Sat Sep 08 15:58:17 CST 2018
     */
    int updateByExample(@Param("record") TbDemo record, @Param("example") TbDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Sat Sep 08 15:58:17 CST 2018
     */
    int updateByPrimaryKeySelective(TbDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Sat Sep 08 15:58:17 CST 2018
     */
    int updateByPrimaryKey(TbDemo record);
}