package com.cycfc.demo.consumer.model;

import java.io.Serializable;

public class TbDemo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_demo.id
     *
     * @mbg.generated Sat Sep 08 16:27:24 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_demo.age
     *
     * @mbg.generated Sat Sep 08 16:27:24 CST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_demo.name
     *
     * @mbg.generated Sat Sep 08 16:27:24 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_demo.sex
     *
     * @mbg.generated Sat Sep 08 16:27:24 CST 2018
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_demo
     *
     * @mbg.generated Sat Sep 08 16:27:24 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_demo.id
     *
     * @return the value of tb_demo.id
     *
     * @mbg.generated Sat Sep 08 16:27:24 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_demo.id
     *
     * @param id the value for tb_demo.id
     *
     * @mbg.generated Sat Sep 08 16:27:24 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_demo.age
     *
     * @return the value of tb_demo.age
     *
     * @mbg.generated Sat Sep 08 16:27:24 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_demo.age
     *
     * @param age the value for tb_demo.age
     *
     * @mbg.generated Sat Sep 08 16:27:24 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_demo.name
     *
     * @return the value of tb_demo.name
     *
     * @mbg.generated Sat Sep 08 16:27:24 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_demo.name
     *
     * @param name the value for tb_demo.name
     *
     * @mbg.generated Sat Sep 08 16:27:24 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_demo.sex
     *
     * @return the value of tb_demo.sex
     *
     * @mbg.generated Sat Sep 08 16:27:24 CST 2018
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_demo.sex
     *
     * @param sex the value for tb_demo.sex
     *
     * @mbg.generated Sat Sep 08 16:27:24 CST 2018
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_demo
     *
     * @mbg.generated Sat Sep 08 16:27:24 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", age=").append(age);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}